config/routes.rb
Rails.application.routes.draw do

  resources :users

  get '/roles/index', to: "roles#index"

  get '/roles/new', to: "roles#new"

  post '/roles/create'

  root 'roles#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

	def index
		@roles=Role.all
	end

	def create
		@role=Role.create(role_params)
		@role.save
		redirect_to roles_index_path
	end

	def new
	end

private
	def role_params
		params.require(:role).permit(:title)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
      @user=User.new(user_params)
      if @user.save
        redirect_to @user
      else
        flash[:error]="passwordi se ne poklapaju konju"
        redirect_to new_user_path
      end
  end

  def show
    @user=User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projekat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/roles/index.html.erb
<% @roles.each do |r| %>
<p> Naziv uloge:<%= r.title %></p><br>
<% end %>
<%= link_to "Dodaj ulogu", roles_new_path %>

app/views/roles/new.html.erb
<%= form_for :role, url: roles_create_path do |f|%>
<%= f.label :naziv %>
<%= f.text_field :title %>
<%= f.submit "Kreiraj ulogu"%>
<% end %>

app/views/users/new.html.erb
<% if flash[:error] %>

<h1><%=flash[:error ]%></h1>
<%end%>

<%= form_for :user, url: users_path do |f| %>

<%= f.label :name, "Ime" %>
<%= f.text_field :name %>
<br>

<%= f.label :email, "mail" %>
<%= f.text_field :email %>
<br>

<%= f.label :password, "password" %>
<%= f.password_field :password %>
<br>

<%= f.label :password_confirmation, "potvrda passworda" %>
<%= f.password_field :password_confirmation %>
<br>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<p>
  Username:<%=@user.name%>
  Email:<%=@user.email%>
</p>